# Generated by Django 5.0.6 on 2024-05-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('user_rating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.insert_movie')),
            ],
        ),
    ]
